name: 🚀 Test Deploy to cPanel

on:
  push:
    branches:
      - master   # or 'main' if that’s your branch name

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from your repository
      - name: 🧱 Checkout repository
        uses: actions/checkout@v4

      # Step 2: Deploy only the files you want
      - name: 🚀 Upload index.html to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftp
          local-dir: ./          # your local repo folder (root)
          server-dir: /public_html/demodomain.com/github/   # your exact path on cPanel
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/**
            **/vendor/**
            **/tests/**
            **/.env
