name: 🚀 Test Deploy to cPanel

on:
  push:
    branches:
      - main   # or master, depending on your repo

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🧱 Checkout repository
        uses: actions/checkout@v4

      - name: 🚀 Upload index.html to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftp
          local-dir: ./
          server-dir: /public_html/demodomain.com/github/
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/**
            **/vendor/**
            **/tests/**
            **/.env
