name: 🚀 Test Deploy to cPanel (SFTP)

on:
  push:
    branches:
      - main   # or master

jobs:
  sftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🧱 Checkout repository
        uses: actions/checkout@v4

      - name: 🚀 Upload via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_SERVER }}
          port: ${{ secrets.SFTP_PORT }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: "./"
          remote_path: "/public_html/demodomain.com/github/"
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/**
            **/vendor/**
            **/.env
